default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

#  database: cap_test

development:
  <<: *default
  database: cap_test_development
